$schema: https://azuremlschemas.azureedge.net/latest/computeInstance.schema.json
name: cpu-automated-test
size: STANDARD_F2S_V2
type: computeinstance
idle_time_before_shutdown: PT30M
idle_time_before_shutdown_minutes: 30
schedules:
  compute_start_stop:
  # Stopping at 10pm UTC
  - action: stop
    state: enabled
    trigger:
      expression: 00 22 * * 0,1,2,3,4,5,6
      start_time: '2023-05-08T11:49:12'
      time_zone: UTC
      type: cron
  # Stopping at 6pm UTC
  - action: stop
    state: enabled
    trigger:
      expression: 00 18 * * 0,1,2,3,4,5,6
      start_time: '2023-05-08T11:49:03'
      time_zone: UTC
      type: cron